name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - run: "git branch --track main origin/main"
      - run: yarn nx affected:lint --base=${{ github.base_ref }} --head=${{ github.head_ref }}
      - run: yarn nx affected:test --base=${{  github.base_ref }} --head=${{ github.head_ref }}
      - run: yarn nx affected:build --base=${{  github.base_ref }} --head=${{ github.head_ref }}
